before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
  - build
  - test
  - coverage
  - deploy



build:
  tags:
    - testing
  stage: build
  script: pwd

test:
  tags:
    - testing
  stage: test
  script: mkdir coverage
  artifacts:
    paths:
      - coverage
      
pages:
  stage: coverage
  tags:
    - testing
  dependencies:
    - test
  script:
    - mv coverage public/
  artifacts:
    paths:
      - public
    
    
    
deploy:
  tags:
    - testing
  stage: deploy
  script: pwd
  
  



